### ISSUE TITLE
`write_ods(append = TRUE)` and `write_ods(update = TRUE)` are still slow

### ISSUE THREAD

**Issue by chainsawriot** [ropensci/readODS#141]
Despite #113 , `append` and `update` are still slow due to the reliance on `xml2`. And this is the last part we need `xml2`.

I need to study the `rapidxml` code to learn how to modify the DOM tree with cpp.

**Comment by pbrohan** [comment]
I would actually guess that it would be faster to simply use a similar method to the current method of writing, and write the sheets with no headers to temp files and then concatenate them together, rather than trying to actually edit the XML tree itself in memory.

I guess you could make massive files by appending files that don't fit in memory this way, so you could write a file that you cannot then read, but it could be argued that this would in fact be the user's fault.

**Comment by chainsawriot** [comment]
@pbrohan Given the fact that `write_ods` can now write list of data frames; an idea similar to yours is to read all sheets from the ODS file as list; modify the content of the list; and then write the list as ODS.

To me, it sounds fine (might still faster than `xml2`). The potential problem is that the roundtrip of `read_ods` and then `write_ods` is not lossless for ODS files produced from other sources (format, date, comments, merged cells and whatnot).
