### ISSUE TITLE
Column Names lack leading and trailing whitespace triming despite trim_ws = TRUE

### ISSUE THREAD

**Issue by brulaz** [ropensci/readODS#185]
As per title,
Column Names lack leading and trailing whitespace triming despite trim_ws = TRUE

**Comment by chainsawriot** [comment]
@brulaz Thank you very much for reporting this. It is not the expected behavior, at least not in line with `readxl`.

I added the test files here: [spaces_colnames.ods](https://github.com/ropensci/readODS/blob/i185/tests/testdata/spaces_colnames.ods) and [spaces_colnames.xlsx](https://github.com/ropensci/readODS/blob/i185/tests/testdata/spaces_colnames.xlsx).

``` r
colnames(readODS::read_ods("~/dev/readODS/tests/testdata/spaces_colnames.ods", trim_ws = TRUE))
#> [1] "     abc    "

colnames(readODS::read_ods("~/dev/readODS/tests/testdata/spaces_colnames.ods", trim_ws = FALSE))
#> [1] "     abc    "

colnames(readxl::read_xlsx("~/dev/readODS/tests/testdata/spaces_colnames.xlsx", trim_ws = TRUE))
#> [1] "abc"

colnames(readxl::read_xlsx("~/dev/readODS/tests/testdata/spaces_colnames.xlsx", trim_ws = FALSE))
#> [1] "     abc    "
```

<sup>Created on 2024-04-10 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
