### ISSUE TITLE
Specifying the "na=NA" argument breaks read_ods()

### ISSUE THREAD

**Issue by thunderbird-1990** [ropensci/readODS#96]
I used to use `df<-read_ods("./file.ods", na=NA)`, but the latest version of readODS shows this error: `Invalid input type, expected 'character' actual 'logical'`

This can be fixed by removing `na=NA` and let `read_ods()` handles blank cells using the default behaviour.

Is this expected?

Also, according to the documentation, the default argument of `read_ods()` is `na = ""`, but it is not clear to me whether `""` is the same as `NA`...

Thanks in advance.

**Comment by chainsawriot** [comment]
@thunderbird-1990 The changes to `read_ods` in v1.8 were actually minimal. Could you please share with me your `file.ods` so that I can give it a test against v1.7 (or even older versions) and v1.8?

In general, `NA` by default is not a character vector (unless you do: `NA_character_`). If the NA field in your `file.ods` is actually "NA", then maybe the correct way of doing this is `na = "NA"`.

**Comment by thunderbird-1990** [comment]
@chainsawriot Thanks for your quick reply.

I am using readODS 1.8.0. My LibreOffice is 7.4.5.1 and my R is 4.2.2.

On my computer, the `na=NA` argument breaks `read_ods()` (`Error: Invalid input type, expected 'character' actual 'logical'`) for any .ods file, but it used to work until very recently.

```
library(readODS)
df<-read_ods("./test.ods", na=NA)
```
This is a minimal .ods file: 
[test.ods](https://github.com/ropensci/readODS/files/10513788/test.ods)

**Comment by chainsawriot** [comment]
@thunderbird-1990 

Thank you very much for the details.

After some digging, we fixed the issue #78 and now `read_ods` is honoring `na`. So, `na=NA` is actually a buggy behavior; please use either `na = c("NA", "")` or the default `na = ""`.

If you must use `na = NA`, use `na = NA_character_`.
